### DISCUSSION TITLE
如何添加作者姓名的多语言设置？

### DISCUSSION THREAD

**Discussion by seekzzh** [hugo-fixit/FixIt#222] [Q&A] [answered]
### Describe the feature you want 描述你的功能需求

目前config文件里作者名称只支持设置唯一值，不能很多地适应多语言。一个替代的解决办法是每篇文章单独设置作者名，但不能显示头像，效果不理想。能否在config添加设置全局多语言作者名称的接口 ？

**Comment by Lruihao** [comment, marked as answer]
该功能已存在，例如：

```toml
[author]
  name = "Lruihao"
  email = "hello@lruihao.cn"
  link = "https://lruihao.cn"

[languages.zh-cn]
   # ...
    [languages.zh-cn.author]
      name = "李四啊"
      email = "world@lruihao.cn"
      link = "https://lruihao.cn"
```
<img width="813" alt="image" src="https://user-images.githubusercontent.com/33419593/195280044-74b0483c-b27a-47e8-8401-8982589e5ce0.png">

<img width="804" alt="image" src="https://user-images.githubusercontent.com/33419593/195280126-940f50d3-3587-496d-bd80-f19e0cd25ce3.png">
