### DISCUSSION TITLE
怎么使用非Gravatar头像？

### DISCUSSION THREAD

**Discussion by Ailontania** [hugo-fixit/FixIt#261] [Q&A] [answered]
### Describe the bug 描述你遇到的错误

v. 0.2.16

设置：    gravatarForce = false

avatar头像依然只能从Gravatar加载，本地资源文件里的头像设置无效。

**Comment by Lruihao** [comment]
1. profile 的头像由 `params.home.profile` 的 `gravatarEmail` 和 `avatarURL` 的值决定，优先级：`gravatarEmail` > `avatarURL`
    ```toml
        # Home page profile
        [params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          avatarURL = "/images/avatar.jpg"
    ```
    **使用本地头像，`gravatarEmail` 为空并设置 `avatarURL` 即可**
2. 文章的头像由 `params.home.profile` 的  `gravatarEmail` 和 `avatarURL` 的值和 `params.page.gravatarForce` 以及作者的邮箱决定
     - 有 `avatarURL` 且 `gravatarForce = false`, 显示本地头像
     - `gravatarForce = true` 且作者邮箱不为空则优先于 `avatarURL` 显示 Gravatar 头像
     - 作者邮箱优先级：文章 frontmatter 定义的 > 站点配置的 `author.email`

     **使用本地头像，`gravatarForce = false` 并设置 `avatarURL` 即可**

**Reply by Ailontania** [reply]
谢谢！

**Comment by Lruihao** [comment, marked as answer]
在 v0.2.18 版本，该功能发生变化，详见 https://github.com/hugo-fixit/FixIt/pull/288 ，所以对于该问题，v0.2.18 版本之后的回答如下：

1. profile 的头像由 `params.home.profile` 的 `gravatarEmail` 和 `avatarURL` 的值决定，优先级：`gravatarEmail` > `avatarURL`
    ```toml
        [params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.jpg"
    ```
    **使用本地头像，`params.gravatar.enable = false` 或 `gravatarEmail` 为空，并设置 `avatarURL` 即可**
3. 文章的头像仅由作者的邮箱（`author.email`）和头像（`author.avatar`）决定
     - 当文章作者名和站点作者名一致时，文章作者配置 > 站点作者配置，缺省值为站点作者配置
     - 当文章未配置作者，视为同上
     - 当文章作者名和站点作者名不一致时，文章作者配置 > 站点作者配置，缺省值为空
 
     **使用本地头像，`params.gravatar.enable = false` 或 作者邮箱（`author.email`）为空，并设置作者头像（`author.avatar`）即可**
