### DISCUSSION TITLE
Partial Encryption with shortcodes not working

### DISCUSSION THREAD

**Discussion by Edz0ro** [hugo-fixit/FixIt#335] [Q&A]
Hello, 

I tried to made partial encryption with shortcodes following this docs : https://fixit.lruihao.cn/documentation/content-management/encryption/

When I copy paste the shortcode for partial encryption it doesn't work. 

So I also tried to init shortcodes for encryption whithout success. There is no error but it's just doesn't show up.

```
{{<script>}} 

document.addEventListener('DOMContentLoaded', () => {fixit.theme.decryptor.initShortCodes()}); 

{{</script>}}
```

Sorry I'm very new to web dev ^^'

the yaml of the encrypted page : 

```
---
title: Encryption test
date: 2022-05-28T11:51:41+08:00
author:
  name: edzoro
  link: 
password: 1212
message: Enter password
tags:
  - Encryption
url: /test
twemoji : true
type: "page"
---
```

Thank you for your help 🙏
