### DISCUSSION TITLE
只有`content/posts/*.md` 文件才会使用 `layouts/posts/single.html`, 有方法应用到全部的md文件吗？

### DISCUSSION THREAD

**Discussion by Aincvy** [hugo-fixit/FixIt#350] [Q&A] [answered]
我目前的操作是 使用`layouts/posts/single.html` 替换了 `layouts/_default/single.html`  

我想询问的是有没有别的方法设置？ 

好像复制目录 `layouts/posts` 到新的目录 `layouts/xxx`  也行？  但是分类多的话， 感觉还是直接覆盖_default 更方便一些。

**Comment by Lruihao** [comment, marked as answer]
不用改模板，在文章前面写上 type: posts 即可

**Reply by Aincvy** [reply]
这样的话， 每篇文章都要加的吧。 

应该是加在这里？ 
```yaml
---
title: "3. 应用的更新以及容器扩缩以及命名空间"
date: 2023-07-29T12:13:25+08:00
draft: false
type: posts
---
```

我好像有一两百篇文章了， 还是直接修改_default 简单一些 🤣
