### DISCUSSION TITLE
front matter menu

### DISCUSSION THREAD

**Discussion by MSeutin** [hugo-fixit/FixIt#352] [Q&A]
I created an md file under a menu ('apps') and tried to make it a submenu of 'apps' but it's not working, here is my front matter:
```
---
title: "First App"
date: 2023-08-02T21:21:53-07:00
draft: false
featuredImage:
featuredImagePreview: 
description:
keywords:
tags: 
categories: 
comment:
seo:
menu:
  main:
    name: 'First App'
    title: whatever
    parent: apps
    params:
      icon: fa-brands fa-readme
---

# First App
this is my second first app
```
