### DISCUSSION TITLE
[BUG] html 格式后缀与 md 冲突，导致不能正常显示页面或者文章

### DISCUSSION THREAD

**Discussion by Mejituu** [hugo-fixit/FixIt#377] [Q&A] [answered]
### Describe the bug 描述你遇到的错误

在每个页面或者文章设置字段 url 为 xxx.html 时，同时配置文件 outputs 也开启了页面 md 输出

实际上
访问 xxx.html 显示的是一个 html 格式的 md 代码
访问 xxx.md 显示的是 md 格式的正常原文件

### Expected behavior 期待的行为

正常通过 xxx.html 访问文章或页面
正常通过 xxx.md 访问文章或页面 原文件

### Build Environment 构建环境

109

### Preview Environment 预览环境

Debian testing

### Additional Information 补充信息

page = ["HTML", "MarkDown"]

url = "about.html"

**Comment by Lruihao** [comment]
<img width="728" alt="image" src="https://github.com/hugo-fixit/FixIt/assets/33419593/6b86c483-4fa9-49c3-8a33-d4e9e87543cf">

默认情况下，Hugo会生成 pretty URLs。要生成 ugly URLs，请更改网站配置：`uglyURLs = true`

- 参见 [URL management](https://gohugo.io/content-management/urls/#appearance)

**Comment by Mejituu** [comment]
之前我也开启了uglyURLs = true，后面因为需要其他页面都是/形式 只是文章需要.html所以，我就取中方法文章内设置url,但是发现与md冲突了，md会覆盖掉.html的请求

**Comment by Lruihao** [comment, marked as answer]
提供一种方案

1. 开启 uglyURLs = true
2. outputFormats 新增一个类型 HTMLPretty

    ```toml
    [HTMLPretty]
      mediaType = "text/html"
      isHTML = true
      noUgly = true
    ```

3. outputs修改 部分输出类型为 HTMLPretty 

    ```toml
    home = ["HTML", "RSS", "JSON", "BaiduUrls"]
    page = ["HTML", "MarkDown"]
    section = ["HTMLPretty", "RSS"]
    taxonomy = ["HTMLPretty"]
    term = ["HTMLPretty", "RSS"]
    ```

4. 由于  posts 和 其他页面都是 page，所以 page 单独设置 url，例如：`url: /about/`
