### DISCUSSION TITLE
SEO - Repetition in the title of all pages

### DISCUSSION THREAD

**Discussion by Kapusch** [hugo-fixit/FixIt#392] [Q&A] [answered]
Hi @Lruihao , your template is really powerful and saved me many days of work, thanks again.

I just discovered my website name is contained in the title of all my pages (under "head" HTML tag), and I wonder if this could be an issue for indexing. I'm a bit uncomfortable with SEO and I would like to clarify why only 30% of my [website](https://www.mauicestclair.fr/) is indexed on Google.

Is it intentional to replicate "name" value (located under "params.header.title") into all pages title?
Can't it slow / block the indexing process from Google?

**Comment by Lruihao** [comment, marked as answer]
@Kapusch Oh sorry, I think the repetition website name in titles will not slow / block down seo collection, because many websites do this, such as: Hugo, facebook, etc. (but i'm not sure...)

If you wanna remove the duplicate parts, I'll consider adding relevant configurations for this.

**Reply by Kapusch** [reply]
Thanks for your feedback @Lruihao !

I have observed recommendations to keep titles shorter than 70 characters long, so I will adapt my titles in first place, but definitely a good idea to add a configuration parameter.

**Reply by Lruihao** [reply]
add `params.withSiteTitle` and `params.titleDelimiter` to support.

```toml
[params]
  # ...
  # FixIt 0.3.0 | NEW whether to add site title to the title of every page
  # remember to set up your site title in `hugo.toml` (e.g. title = "title")
  withSiteTitle = true
  # FixIt 0.3.0 | NEW title delimiter when the site title is be added to the title of every page
  titleDelimiter = "-"
```
