### DISCUSSION TITLE
How to override article-font-size?

### DISCUSSION THREAD

**Discussion by adduserwyw** [hugo-fixit/FixIt#418] [Q&A] [answered]
Hi, I wanna override article-font-size and/or article-font-style, try to override global-font-size and it also changed toc-font-size.

Thanks in advance.

**Comment by Lruihao** [comment, marked as answer]
Try this in `assets/css/_custom.scss`:

```scss
#content {
  font-size: 14px; // any size you expect
}
```
