### DISCUSSION TITLE
tags/categories 的首字母默认大写问题

### DISCUSSION THREAD

**Discussion by Zack4396** [hugo-fixit/FixIt#427] [Q&A] [answered]
Hi 大家好

请教一个 tags/categories 的首字母默认大写问题

如下图, 这里写的标签/分类 的首字母默认都会大写，有什么办法可以关掉么?

![1](https://github.com/hugo-fixit/FixIt/assets/38660711/1f0acb91-5754-48af-9218-31968f0ff329)

我看官网的截图里面, 是有大小写区分的 (如下图所示)
![image](https://github.com/hugo-fixit/FixIt/assets/38660711/e9514c3a-e033-4246-b4e9-e359d70f0c74)

**Comment by Zack4396** [comment, marked as answer]
谢谢 FixIt 群友帮助

解决办法

添加 `titleCaseStyle = "none"`

> 来源 https://gohugo.io/getting-started/configuration/#configure-title-case

**hugo.toml**

```toml
baseURL = ""
theme = "FixIt"

# 新加一行
titleCaseStyle = "none"
```

**Comment by Lruihao** [comment]
```toml
titleCaseStyle = "none"
# 或者
capitalizeListTitles = false
```
