### DISCUSSION TITLE
Archives 页面不存在

### DISCUSSION THREAD

**Discussion by tearizz** [hugo-fixit/FixIt#455] [Q&A] [answered]
写好了文章后，在archives页面找不到文章，但是在别的页面都可以正常看到文章，不知道是哪里出了问题？
![image](https://github.com/hugo-fixit/FixIt/assets/81475774/60cac0ea-cff8-48d7-aa2b-da2d7f6ce343)
![image](https://github.com/hugo-fixit/FixIt/assets/81475774/8da77329-1fc9-4ac4-96d3-34888801b402)

**Comment by Lruihao** [comment, marked as answer]
在你的配置文件中加入：

```toml
[mediaTypes]
  # Options to make output .md files
  [mediaTypes."text/markdown"]
    suffixes = ["md"]
  # Options to make output .txt files
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

[outputFormats]
  # Options to make output .md files
  [outputFormats.MarkDown]
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.3.0 | NEW Options to make output /archives/index.html file
  [outputFormats.archives]
    path = "archives"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
  # FixIt 0.3.0 | NEW Options to make output /offline/index.html file
  [outputFormats.offline]
    path = "offline"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
  # FixIt 0.3.0 | NEW Options to make output readme.md file
  [outputFormats.README]
    baseName = "readme"
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.3.0 | CHANGED Options to make output baidu_urls.txt file
  [outputFormats.baidu_urls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON", "archives"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]
 ```
 
或者直接从主题中继承配置（**推荐**）：

```toml
[mediaTypes]
  _merge = "shallow"

[outputFormats]
  _merge = "shallow"

[outputs]
  _merge = "shallow"
```
