### DISCUSSION TITLE
内置 Shortcodes | FixIt

### DISCUSSION THREAD

**Discussion by giscus** [hugo-fixit/FixIt#456] [General]
# 内置 Shortcodes | FixIt

Hugo 提供了多个内置的 Shortcodes, 以方便作者保持 Markdown 内容的整洁。

https://fixit.lruihao.cn/zh-cn/docs/content-management/shortcodes/built-in/

**Comment by sincerely-hello-world** [comment]
看起来shortcode是对markdown格式的扩充。

对了，请问一下 本文中的 `解锁可编辑代码块`功能是如何实现的？  也是 shortcode么?

**Reply by Lruihao** [reply]
首先需要设置和主题一样的渲染配置

```toml
[markup]
  [markup.highlight]
    _merge = "shallow"

  [markup.goldmark]
    _merge = "shallow"
```

然后这个功能应该是默认开启的，如果不生效，检查一下下面这个参数。

```toml
[params.page.code]
  edit = true
```
