### DISCUSSION TITLE
How to display line numbers in code block?

### DISCUSSION THREAD

**Discussion by kongjun18** [hugo-fixit/FixIt#485] [Q&A] [answered]
How to display line numbers in code block?

**Comment by Lruihao** [comment, marked as answer]
> How to display line numbers in code block?

```toml
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ########## necessary configurations ##########
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    ########## necessary configurations ##########
    guessSyntax = true
```

or

```toml
[markup]
  [markup.highlight]
    _merge = 'shallow'
```
