### DISCUSSION TITLE
Getting rid of brands in posts

### DISCUSSION THREAD

**Discussion by Nevarro** [hugo-fixit/FixIt#500] [General]
When I create a new post, in the footer there's the default icons and links for X, Facebook and Weibo. How and where can I deactivate those?

<img width="162" alt="SCR-20240903-muwr" src="https://github.com/user-attachments/assets/30fccfa3-6588-4c1f-838c-c0f2bbd27b74">

Any help is much appreciated.

Disclaimer: I'm completely new to Hugo and this theme.

**Comment by Lruihao** [comment]
Config at `params.page.share` scope：

```toml
[params]
  [params.page]
    # social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

```
