### DISCUSSION TITLE
Markdown 扩展语法 | FixIt

### DISCUSSION THREAD

**Discussion by giscus** [hugo-fixit/FixIt#512] [General]
# Markdown 扩展语法 | FixIt

这篇文章展示了扩展的 Markdown 语法和格式。

https://fixit.lruihao.cn/zh-cn/docs/content-management/markdown-syntax/extended/

**Comment by deepreadingnet** [comment]
zan

**Comment by realjimmy** [comment]
请问，文章末尾的“相关内容”是怎么添加的呢？推荐逻辑是什么呢？感谢回复。

**Reply by Lruihao** [reply]
```toml
    # FixIt 0.3.0 | 新增 相关内容配置 (https://gohugo.io/content-management/related/)
    [params.page.related]
      enable = false
      count = 5
```
