### DISCUSSION TITLE
Help with upgrade

### DISCUSSION THREAD

**Discussion by salvari** [hugo-fixit/FixIt#599] [Q&A] [answered]
I need help with `[social]` configuration.
I have been using FixIt v0.3.8 for a long time. I'm trying now to upgrade to v0.3.20 but I have a problem with social parameters.

I was using this section in file `params.toml` Mastodon config in v0.3.8 (works fine):
```toml
[social]
 [social.Mastodon]
   id = "@salvari"
   prefix = "https://mastodon.gal/"
   title = "Mastodon"
```
In release v0.3.20 (hugo extended v0.147.2) with the same code I've got an error:
```
ERROR Invalid Mastodon configuration: maps.Params{"id":"@salvari", "prefix":"https://mastodon.gal/", "title":"Mastodon"}
ERROR logged 1 error(s)
```
If I change my file `params.toml` to include:
```toml
[social]
 [Mastodon]
   id = "@salvari"
   prefix = "https://mastodon.gal/"
   title = "Mastodon"
```
I don't get any error message but the home page has no link to my mastodon profile.
I've tried also `[mastodon]` instead of `[Mastodon]`

**Comment by Lruihao** [comment, marked as answer]
It's maybe a bug cause by https://github.com/hugo-fixit/FixIt/pull/559

However, there is a quick solution, like this:

```toml
[social]
  [social.myMastodon]
    id = "@salvari"
    prefix = "https://mastodon.gal/"
    title = "Mastodon"
    [social.myMastodon.icon]
      Class = "fa-brands fa-mastodon fa-fw"
```
