### DISCUSSION TITLE
[BUG]  目录所有文章-最近更新，本地与远程打包不同，数据不对

### DISCUSSION THREAD

**Discussion by real-jacket** [hugo-fixit/FixIt#91] [Q&A] [answered]
### Describe the bug 描述你遇到的错误

本地打包跟 github action/vercel 上打包的不一样。
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/36723264/160293204-620aa2eb-bbf6-4c81-8790-c04e8e4fb4ba.png">
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/36723264/160293218-c51275cd-af4e-4c95-aaf7-5c1c8d60d8de.png">
上面为正确的本地打包结果，下面为利用第三方 ci/cd 打包的错误结果，那个最近更新文章的不对。
都是运行的 `hugo --minify` 进行打包，现在不清楚是哪个地方出问题了，参考大佬的配置进行的，希望能帮忙看一下问题所在。

个人博客代码仓库：https://github.com/real-jacket/hugo-blog

### Expected behavior 期待的行为

希望本地与远程保持一致

### Build Environment 构建环境

本地机器：Macos 14寸 Monterey 12.3
本地的 hugo 版本：hugo v0.96.0+extended darwin/arm64 BuildDate=unknown
远程系统：ubuntu 20.4
远程的：hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z

**Comment by Lruihao** [comment]
## 原因

> By default, Vercel ignores certain files and folders for security and performance reasons, preventing them from being uploaded during the deployment process. #ignored-files-and-folders

出现这个问题的原因是因为vercel为了安全起见默认禁止了部署根目录的 `.git` 目录上传，所以在vercel部署时，没有获取到git的时间，进而Hugo FixIt回去寻找文件的更新时间作为更新日期，所以vercel部署才会出现每次打包，更新日期都是当天或者因为cache是最近几天。

## 解决办法
手动clone项目代替vercel的自动clone，从而使得 `.git` 不在部署的根目录而得以上传。

几个可用的vercel配置可参考
https://github.com/Lruihao/FixIt/wiki/Vercel-Config

**Reply by real-jacket** [reply]
感谢回复，我大概理解了，我马上试试

**Reply by real-jacket** [reply]
我按照 copy 你的推荐配置，解决了这个问题。但是，它的博客配置读的不是我的而是主题的，posts 里的文章也是混合的。所以我按照你的配置进行了改造，发现失效了。还是跟之前一样。
```bash
# install
git clone https://github.com/real-jacket/hugo-blog.git Blog && cd Blog && git submodule update --init && rm -rf .git && cp -rf ../.git ./  && git checkout $VERCEL_GIT_COMMIT_SHA


# build
hugo -v --source=Blog  --gc --minify

# output
Blog/public
```

**Reply by real-jacket** [reply]
我在 github action 上有同样的问题，我看了一下你的博客的 action 配置，发现基本一样的，我比较奇怪你的怎么没有这个问题？

**Reply by Lruihao** [reply]
我看了一下你的配置好像都没什么问题，到底问题在哪我暂时也不知道

**Reply by real-jacket** [reply]
唉，折腾了一个周末了。暂时也没弄明白为什么，只能先本地上传了，后续要遇到类似的情况或者有新的解决方案，麻烦@一下我，万分感激🙏。

**Reply by Lruihao** [reply]
> 唉，折腾了一个周末了。暂时也没弄明白为什么，只能先本地上传了，后续要遇到类似的情况或者有新的解决方案，麻烦@一下我，万分感激🙏。

嗯嗯，这个vercel很奇怪，我刚刚重新配置了一下，好像配置也失效了，我这几天再看看，找到解决办法，再@你

**Reply by hiifong** [reply]
你可以让vercel只克隆public文件夹，可以参考我的博客：https://52at.ml/hugo/ ，写得不是很好，但是你可以参考怎么使用两个仓库部署博客，也是我的博客正在使用的方案。

**Reply by hiifong** [reply]
> 你可以让vercel只克隆public文件夹，可以参考我的博客：https://52at.ml/hugo/ ，写得不是很好，但是你可以参考怎么使用两个仓库部署博客，也是我的博客正在使用的方案。

@real-jacket

**Reply by real-jacket** [reply]
感谢回复，这个问题是由于 github action 与 vercel 跟本地打包的产物不一致引起的，原因在于 html 的生成的时间点有问题。具体的你可以去对比一下。至于你说的两个仓库，一个用来的储存 blog 代码，一个用来储存打包后的静态资源（用来部署的博客项目），对吗。目前我也是在使用的这种方案，但是这个方案跟这个问题没有关系，我发现你的博客也是用的 github action 去处理的，貌似也存在这样的问题哦。目前的解决方案是不用 github action 本地打包上传 publc，前提这一切都建立在本地打包的基础上，但是这就没有多大意义了。

**Reply by hiifong** [reply]
> 感谢回复，这个问题是由于 github action 与 vercel 跟本地打包的产物不一致引起的，原因在于 html 的生成的时间点有问题。具体的你可以去对比一下。至于你说的两个仓库，一个用来的储存 blog 代码，一个用来储存打包后的静态资源（用来部署的博客项目），对吗。目前我也是在使用的这种方案，但是这个方案跟这个问题没有关系，我发现你的博客也是用的 github action 去处理的，貌似也存在这样的问题哦。目前的解决方案是不用 github action 本地打包上传 publc，前提这一切都建立在本地打包的基础上，但是这就没有多大意义了。

我的好像没有这个问题吧

**Reply by real-jacket** [reply]
> > 感谢回复，这个问题是由于 github action 与 vercel 跟本地打包的产物不一致引起的，原因在于 html 的生成的时间点有问题。具体的你可以去对比一下。至于你说的两个仓库，一个用来的储存 blog 代码，一个用来储存打包后的静态资源（用来部署的博客项目），对吗。目前我也是在使用的这种方案，但是这个方案跟这个问题没有关系，我发现你的博客也是用的 github action 去处理的，貌似也存在这样的问题哦。目前的解决方案是不用 github action 本地打包上传 publc，前提这一切都建立在本地打包的基础上，但是这就没有多大意义了。
> 
> 我的好像没有这个问题吧

你所有的文章最近更新的都是 5.10 吗?

**Reply by real-jacket** [reply]
> ![image](https://user-images.githubusercontent.com/89133723/168214037-3c9dddb7-041b-4185-928e-ac49d83922cd.png) 请仔细看一下我的action，我是强制推送的，具体可以看一下我的[action](https://github.com/hiifong/myactions.git)

这个跟推送没关系，你 build 的时候的html 文件已经是不正确的了，我对比了本地的产物跟云端构建的产物的。最近更新那块的 html 是有问题的

**Reply by hiifong** [reply]
> > ![image](https://user-images.githubusercontent.com/89133723/168214037-3c9dddb7-041b-4185-928e-ac49d83922cd.png) 请仔细看一下我的action，我是强制推送的，具体可以看一下我的[action](https://github.com/hiifong/myactions.git)
> 
> 这个跟推送没关系，你 build 的时候的html 文件已经是不正确的了，我对比了本地的产物跟云端构建的产物的。最近更新那块的 html 是有问题的

![image](https://user-images.githubusercontent.com/89133723/168243049-c21733a3-8c5c-46aa-90a4-80e07c68847d.png)
不好意思我看这个截图以为是文章没有同步

**Reply by hiifong** [reply]
> > ![image](https://user-images.githubusercontent.com/89133723/168214037-3c9dddb7-041b-4185-928e-ac49d83922cd.png) 请仔细看一下我的action，我是强制推送的，具体可以看一下我的[action](https://github.com/hiifong/myactions.git)
> 
> 这个跟推送没关系，你 build 的时候的html 文件已经是不正确的了，我对比了本地的产物跟云端构建的产物的。最近更新那块的 html 是有问题的

![image](https://user-images.githubusercontent.com/89133723/168251433-8a91a003-280a-4510-89da-a855013c1c80.png)
是这个效果吗

**Reply by real-jacket** [reply]
> 

对，目前看来你这个应该是正确的，你应该也是在本地打包的吧

**Reply by hiifong** [reply]
> > 
> 
> 这个不就有问题吗， 明显你最近不是把所有的文章都更新了一遍吧，你再仔细看我的问题对比你就能够发现了

那我这个符合你的预期结果了吗

**Reply by real-jacket** [reply]
目前看起来应该符合，请问你怎么改动的，我这边可以试一下看看效果

**Reply by hiifong** [reply]
> 目前看起来应该符合，请问你怎么改动的，我这边可以试一下看看效果

请参考这个[action](https://github.com/hiifong/myactions)

**Reply by real-jacket** [reply]
目前参照你的 action 进行改动，基本就是 build 的那步新增了 --enableGitInfo --ignoreCache 这两个参数 。但是依旧没有生效，是不是还有什么其它地方的配置，这是我的 github action ：
```yml
name: github pages

on:
  push:
    branches:
      - master
      # - dev

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Hugo repo
        uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify --enableGitInfo --ignoreCache

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: xx/xx
          publish_branch: master
          publish_dir: ./public
          force_orphan: true

      - name: Push search json
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_INDEX_FILE: ${{ secrets.ALGOLIA_INDEX_FILE }}
        run: |
          npm install
          npm run algolia

```
