### ISSUE TITLE
[FEATURE] 添加飞书社交链接

### ISSUE THREAD

**Issue by hiifong** [hugo-fixit/FixIt#175]

**Comment by Lruihao** [comment]
有参考链接吗

**Comment by hiifong** [comment]
> 有参考链接吗

添加联系人方式：

- [链接格式：hiifong申请添加你为联系人，点击链接处理](hiifong申请添加你为联系人，点击链接处理 https://www.feishu.cn/invitation/page/add_contact/?token=) 
- 二维码

**Comment by Lruihao** [comment]
我最近有些忙，暂时没时间处理。你可以在配置文件里先自定义，比如：

```toml
[params.social]
  [params.social.Mastodon]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 0
    # your social ID
    id = "@xxxx"
    # prefix of your social link
    prefix = "https://mastodon.social/"
    # content hovering on the icon
    title = "Mastodon"
```
