### ISSUE TITLE
[FEATURE] add pace support

### ISSUE THREAD

**Issue by Lruihao** [hugo-fixit/FixIt#190]
- https://github.com/CodeByZach/pace
- https://github.com/next-theme/hexo-theme-next/search?q=pace

```toml
# Progress bar in the top during page loading.
# For more information: https://github.com/CodeByZach/pace
[params.pace]
  enable = false
  # All available colors:
  # black | blue | green | orange | pink | purple | red | silver | white | yellow
  color = "blue"
  # All available themes:
  # big-counter | bounce | barber-shop | center-atom | center-circle | center-radar | center-simple
  # corner-indicator | fill-left | flat-top | flash | loading-bar | mac-osx | material | minimal
  theme = "minimal"
```
