### ISSUE TITLE
[FEATURE] add reading progress bar support

### ISSUE THREAD

**Issue by Lruihao** [hugo-fixit/FixIt#191]
```toml
# Reading progress bar
[params.readingProgress]
  enable = false
  # Available values: left | right
  start = "left"
  # Available values: top | bottom
  position = "top"
  reversed = false
  light = ""
  dark = ""
  height = "2px"
```
