### ISSUE TITLE
[FEATURE] add b2t scroll percent support

### ISSUE THREAD

**Issue by Lruihao** [hugo-fixit/FixIt#192]
```toml
[params.back2top]
  enable = true
  # Scroll percent label in b2t button.
  scrollpercent = false
```
