### ISSUE TITLE
[FEATURE] add params to close wordcount and readingTime in post

### ISSUE THREAD

**Issue by Lruihao** [hugo-fixit/FixIt#209]
### Describe the feature you want 描述你的功能需求

add params to close wordcount and readtime in post

### Useful reference 有价值的参考

```toml
[params.page]
  # ...
  wordCount = true
  readingTime = true
```
