### ISSUE TITLE
Twikoo在手机端无法正常显示

### ISSUE THREAD

**Issue by zyyjade** [hugo-fixit/FixIt#215]
### Describe the bug 描述你遇到的错误

Twikoo评论区在PC端显示正常，在手机端转圈圈，请问这是主题适配问题还是Twikoo的bug？
评论区示例：https://zyyjade.github.io/program-hugoblog/

### Expected behavior 期待的行为

手机端正常显示Twikoo评论区

### Screenshots 屏幕截图

**电脑端截图**：
[![xMRfL4.png](https://s1.ax1x.com/2022/10/03/xMRfL4.png)](https://imgse.com/i/xMRfL4)
<br>
**手机端截图**：
[![xMR4eJ.jpg](https://s1.ax1x.com/2022/10/03/xMR4eJ.jpg)](https://imgse.com/i/xMR4eJ)

### Build Environment 构建环境

- OS：Windows 10 64bit
- 主题版本：0.2.16
- Hugo 版本：v0.104.0 extended windows/amd64
- Twikoo 部署方式：私有部署

### Preview Environment 预览环境

- OS：Windows 10 + Android
- 浏览器：Firefox + Kiwi 浏览器

### Additional Information 补充信息

```toml
[params.page.comment.twikoo]
   enable = true
   envId = "出于数据安全，不展示"
   region = ""
   path = ""
   visitor = true
   commentCount = true
   # 当 `params.page.lightgallery` 启用时生效
   lightgallery = false
```
