### ISSUE TITLE
[FEATURE] Tags 根据数量改变大小

### ISSUE THREAD

**Issue by Ayouuuu** [hugo-fixit/FixIt#235]
### Describe the feature you want 描述你的功能需求

现在标签默认是由大到小排序，是否可由 Tags(标签) 根据数量改变文本的大小?

### Useful reference 有价值的参考

https://a.biugle.cn/tags/

**Comment by Lruihao** [comment]
@pandaoh 快看你的博客😊

**Comment by Lruihao** [comment]
```toml
# TagCloud settings for tags page.
[params.tagcloud]
  enable = false
  min= 12 # Minimum font size in px
  max= 30 # Maximum font size in px
```
