### ISSUE TITLE
[BUG] 多语言 404 页面默认只生效默认语言

### ISSUE THREAD

**Issue by Mejituu** [hugo-fixit/FixIt#277]
### Describe the bug 描述你遇到的错误

在多语言 404 页面默认只生效默认语言，比如我有俩个语言 zh-cn en，在404情况下只会显示默认语言的404.html，也就是/404.html

### Expected behavior 期待的行为

在默认语言下 404 -> /404.html
在不是默认语言下 404 -> /languageCode/404.html

### Build Environment 构建环境

hugo 109 or 110

### Preview Environment 预览环境

Debian testing KDE

**Comment by Mejituu** [comment]
文件是存在的，但是不会根据语言切换404文件，导致在不是默认语言且是404情况下，显示的与选择的语言不相关（包括菜单等等）

**Comment by Lruihao** [comment]
这个问题属于服务器部署相关的问题了，例如：

1. Netlify 部署可以配置 _redirects 文件

    ```
    /zh-cn/* /zh-cn/ 404.html 404
    ```
2. Vercel 部署，详见 [Custom 404 Page](https://vercel.com/guides/custom-404-page#what-if-i-need-to-name-my-404-file-something-different)

```json
{
  "routes": [
    {
      "handle": "filesystem"
    },
    {
      "src": "/zh-cn/(.*)",
      "status": 404,
      "dest": "/zh-cn/404.html"
    },
    {
      "src": "/(.*)",
      "status": 404,
      "dest": "/404.html"
    }
  ]
}
```

3.  hugo 开发模式（`hugo server`），详见 [Configure server](https://gohugo.io/getting-started/configuration/#configure-server)

```toml
[[redirects]]
  from = '/zh-cn/**'
  status = 404
  to = '/zh-cn/404.html'
[[redirects]]
  from = '/**'
  status = 404
  to = '/404.html'
```
