### ISSUE TITLE
[BUG] 当配置了 waline 评论时，无法根据 URL 最后一级访问文章对应位置

### ISSUE THREAD

**Issue by For-December** [hugo-fixit/FixIt#349]
### Describe the bug 描述你遇到的错误

场景：
- 前提：使用 waline 评论
- 将带有 `#标题` 的 URL 分享给其他人时（如：截图里的 `#服务器安全` ）
- 预期结果是打开链接直接跳转到此标题位置
- 实际却是打开链接后在文章起始处

### Expected behavior 期待的行为

等大佬修复

### Screenshots 屏幕截图

![image](https://github.com/hugo-fixit/FixIt/assets/100057209/11ce1690-11f2-474f-abd7-19fc809388ea)
关于评论的配置：
enable = false 时可以正常转跳

![image](https://github.com/hugo-fixit/FixIt/assets/100057209/bcb15e0f-c760-4e7f-9b35-f5e06c56200a)

### Build Environment 构建环境

- hugo：0.115.4_extended
- 主题：FixIt 0.2.18

### Preview Environment 预览环境

- OS: [Windows 10]
- Brower [Chrome, Edge]

### Additional Information 补充信息

waline 使用了独立部署的后端

**Comment by Lruihao** [comment]
未知原因，无法复现。

![QQ20231027-103006-HD](https://github.com/hugo-fixit/FixIt/assets/33419593/c6fedadd-6154-4997-bb79-965f6c7b999e)

**Comment by For-December** [comment]
用下面这个配置可以复现吗（自己部署的评论区）
其他配置默认就行，只改serverURL `https://comment.fordece.cn`
```toml
[params.page.comment.waline]
        enable = true
        serverURL = "https://comment.fordece.cn"
        pageview = true # FixIt 0.2.15 | NEW
        emoji = [
        "https://unpkg.com/@waline/emojis@1.1.0/bilibili",
        "https://unpkg.com/@waline/emojis@1.1.0/tieba",
        "//unpkg.com/@waline/emojis@1.1.0/weibo"
        ]
        meta = ["nick", "mail", "link"]
        requiredMeta = []
        login = "enable"
        wordLimit = 0
        pageSize = 10
        imageUploader = true # FixIt 0.2.15 | NEW
        highlighter = true # FixIt 0.2.15 | NEW
        comment = true # FixIt 0.2.15 | NEW
        texRenderer = false # FixIt 0.2.16 | NEW
        search = true # FixIt 0.2.16 | NEW
        recaptchaV3Key = "" # FixIt 0.2.16 | NEW
        reaction = false # FixIt 0.2.18 | NEW
```
