### ISSUE TITLE
Add withSiteTitle params

### ISSUE THREAD

**Issue by Lruihao** [hugo-fixit/FixIt#395]
Hi @Lruihao , your template is really powerful and saved me many days of work, thanks again.

I just discovered my website name is contained in the title of all my pages (under "head" HTML tag), and I wonder if this could be an issue for indexing. I'm a bit uncomfortable with SEO and I would like to clarify why only 30% of my [website](https://www.mauicestclair.fr/) is indexed on Google.

Is it intentional to replicate "name" value (located under "params.header.title") into all pages title?
Can't it slow / block the indexing process from Google?

_Originally posted by @Kapusch in https://github.com/hugo-fixit/FixIt/discussions/392_

**Comment by Lruihao** [comment]
add `params.withSiteTitle` and `params.titleDelimiter` to support.

```toml
[params]
  # ...
  # FixIt 0.3.0 | NEW whether to add site title to the title of every page
  # remember to set up your site title in `hugo.toml` (e.g. title = "title")
  withSiteTitle = true
  # FixIt 0.3.0 | NEW title delimiter when the site title is be added to the title of every page
  titleDelimiter = "-"
```
