### ISSUE TITLE
refactor busuanzi

### ISSUE THREAD

**Issue by Lruihao** [hugo-fixit/FixIt#472]
## TODO list

- [x] 默认不蒜子改为 https://github.com/EvanNotFound/vercount
- [x] 顶层配置参数改为 `params.busuanzi`
- [x] 提供配置保留原不蒜子逻辑

## Why do this?

不蒜子是一个很好的网站计数器，但是它的缺点也很明显：

- 不蒜子速度慢，不稳定，经常会出现 502 错误。
- 不蒜子的代码已经过时，使用的是 Referrer 方法进行统计，这种方法在移动端 / Firefox / Safari 上统计不准确。[^1]
- 不蒜子的代码使用的是 JSONP 回调，这种方法容易受到 CSRF 攻击，威胁网站安全。[^2]

[^1]: [不蒜子在 Safari 中计数异常](https://blog.cxzlw.top/2023/10/03/busuanzi-bug/)
[^2]: [JSONP](https://en.wikipedia.org/wiki/JSONP)

## How to upgrade?

移除 `params.ibruce` 配置，新增 `params.busuanzi` 配置，格式如下：

```toml
# FixIt 0.3.10 | NEW Busuanzi count
[params.busuanzi]
  # whether to enable busuanzi count
  enable = false
  # busuanzi count core script source. Default is https://vercount.one/js
  source = "https://vercount.one/js"
  # whether to show the site views
  siteViews = true
  # whether to show the page views
  pageViews = true
```
