### ISSUE TITLE
Refactor RSS template

### ISSUE THREAD

**Issue by Lruihao** [hugo-fixit/FixIt#488]
- [zhangxinxu feed](https://www.zhangxinxu.com/wordpress/feed/)
- [RSS intro](https://www.cnblogs.com/tuyile006/p/3691024.html)

---

- [ ] hugo-fixit/hugo-atom-feed#1
- [x] add params.feed 

```toml
# Feed config for RSS, Atom and JSON Feed.
[params.feed]
  limit = -1
  # Front matter support ( .Param "feed').fullText
  fullText = false
```

- [x] Front matter change: hiddenFromRss => hiddenFromFeed
- [x] featuredimage in RSS and JSON feed
- [x] author name format compatibility ([hugo embedded rss.xml#L2-L31](https://github.com/gohugoio/hugo/blob/98aa53648a037e63df65b975786773a0ed95711a/tpl/tplimpl/embedded/templates/_default/rss.xml#L2-L31))
