### ISSUE TITLE
[BUG] Catalog number cannot be configured | 目录编号无法配置

### ISSUE THREAD

**Issue by Tim-Saijun** [hugo-fixit/FixIt#505]
### Describe the bug 描述你遇到的错误

主题有如下配置：
``` 
[params.page.heading]
      # FixIt 0.3.6 | 新增 是否自动大写标题
      capitalize = false
      # 配合 `markup.tableOfContents.ordered` 参数使用
      [params.page.heading.number]
        # 是否启用自动标题编号
        enable = true
```
但对于特定的某一篇文章，我想禁用自动编号，在frontmatter里面配置:
```
heading:
  number:
    enable: false
```
这样做对目录并不生效

### Screenshots 屏幕截图

![image](https://github.com/user-attachments/assets/037bb782-c53b-48ad-95ef-92c8848d6b8c)

**Comment by Lruihao** [comment]
## Params change

```toml
[params]
  # Table of the contents config
  [params.page.toc]
    # ...
    # FixIt 0.3.12 | NEW supersede `markup.tableOfContents` settings
    ordered = false
    startLevel = 2
    endLevel = 6
  [params.page.heading]
  # FixIt 0.3.3 | NEW whether to capitalize automatic text of headings
    capitalize = false
    # FixIt 0.3.12 | CHANGED must set `params.page.toc.ordered` to true
    [params.page.heading.number]
      # ...
```
## Front matter change

```yml
# Don't show number in TOC and headings
toc:
  ordered: false
```
