### ISSUE TITLE
[FEATURE] 再次浏览文章时，自动转到上次阅读位置

### ISSUE THREAD

**Issue by fangd123** [hugo-fixit/FixIt#55]

**Comment by Lruihao** [comment]
目前可以通过锚点定位。

---
文章定位应该和浏览百分比是一个东西，你有什么可以参考的网站或者插件吗

**Comment by fangd123** [comment]
我也在找这方面的解决方案

**Comment by Lruihao** [comment]
已支持页面自动保存书签功能

```toml
[params]
  # ...
  # FixIt 0.2.16 | NEW Auto Bookmark Support
  # If true, save the reading progress when closing the page.
  autoBookmark = false
```
