### ISSUE TITLE
[BUG] Mobile Theme Switch Button Disappears When `autoTranslate` (`cmpt-translate`) is Enabled

### ISSUE THREAD

**Issue by msavdert** [hugo-fixit/FixIt#597]
### Describe the bug 描述你遇到的错误

**Describe the bug**
The theme switch button (light/dark mode toggle) is not visible in the header/menu on mobile devices *only* when the `autoTranslate` feature is enabled (`params.autoTranslate.enable = true`). When `autoTranslate` is disabled, the theme switch button appears correctly on mobile devices. The button works as expected on desktop browsers regardless of the `autoTranslate` setting.

This issue seems related to the injection of partials from the `cmpt-translate` component, specifically the `inject/translate-menu-mobile.html` partial.

**To Reproduce**

1.  Set up a Hugo site using the FixIt theme (version 0.3.X).
2.  Enable the `autoTranslate` feature in params.toml:
    ````toml
    [autoTranslate]
      enable = true
      service = 'client.edge' # Or any other service
      # ... other settings
    ````
3.  Configure `customPartials` in params.toml to use the `cmpt-translate` partials, ensuring `menuMobile` is included:
    ````toml
    [customPartials]
      # ... other partials
      menuMobile = [ "inject/translate-menu-mobile.html", ]
      assets = [ "inject/cmpt-translate.html", ]
      # ... other partials
    ````
    *(These partials likely come from `https://github.com/hugo-fixit/cmpt-translate`)*
4.  Build or serve the site (`hugo server`).
5.  Open the site on a mobile device (e.g., iPhone Safari) or using browser developer tools in mobile emulation mode.
6.  Observe that the theme switch button is missing from the mobile header/menu.
7.  Now, set `enable = false` in the `[autoTranslate]` section of params.toml.
8.  Rebuild/refresh the site and view it on the mobile device again.
9.  Observe that the theme switch button is now visible and functional.

**Expected behavior**
The theme switch button should be visible and functional on mobile devices even when the `autoTranslate` feature and its associated partials (`cmpt-translate`) are enabled.

**Reference / Example**
This behavior might be observable on sites using both FixIt and the cmpt-translate component, potentially including the theme author's site [https://lruihao.cn/](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) if viewed on a mobile device with translation features enabled (though its current configuration might differ).

**Environment:**
*   Hugo version: `latest`
*   FixIt theme version: `0.3.X` (as specified in params.toml)
*   Hugo Modules: Using `cmpt-translate` (likely via Hugo Modules fetch or similar)
*   Browser: Mobile Safari on iOS [Specify iOS version if known], also reproducible in Desktop Chrome/Firefox using mobile emulation.
*   OS: macOS / iOS

**Possible Cause / Additional context**
It seems likely that the `inject/translate-menu-mobile.html` partial, when injected into the mobile menu structure, conflicts with the existing theme elements or JavaScript responsible for rendering/managing the theme switch button on mobile views. The injected code might be altering the DOM structure in a way that hides or removes the button, or causing a CSS/JS conflict.

Please let me know if any further information or testing is required. Thank you!
